// This class was generated from com.antlersoft.yaaap.ISavedState by a tool
// Do not edit this file directly! PLX THX
package com.antlersoft.patchyamp.db;

public abstract class AbstractSavedState extends com.antlersoft.android.dbimpl.ImplementationBase implements ISavedState {

    public static final String GEN_TABLE_NAME = "SAVED_STATE";
    public static final int GEN_COUNT = 2;

    // Field constants
    public static final String GEN_FIELD_CURRENTCONNECTIONID = "CURRENTCONNECTIONID";
    public static final int GEN_ID_CURRENTCONNECTIONID = 0;
    public static final String GEN_FIELD_CONNECTIONVALID = "CONNECTIONVALID";
    public static final int GEN_ID_CONNECTIONVALID = 1;

    // SQL Command for creating the table
    public static String GEN_CREATE = "CREATE TABLE SAVED_STATE (" +
    "CURRENTCONNECTIONID INTEGER," +
    "CONNECTIONVALID INTEGER" +
    ")";

    // Members corresponding to defined fields
    private long gen_currentConnectionId;
    private boolean gen_connectionValid;


    public String Gen_tableName() { return GEN_TABLE_NAME; }

    // Field accessors
    public long getCurrentConnectionId() { return gen_currentConnectionId; }
    public void setCurrentConnectionId(long arg_currentConnectionId) { gen_currentConnectionId = arg_currentConnectionId; }
    public boolean getConnectionValid() { return gen_connectionValid; }
    public void setConnectionValid(boolean arg_connectionValid) { gen_connectionValid = arg_connectionValid; }

    public android.content.ContentValues Gen_getValues() {
        android.content.ContentValues values=new android.content.ContentValues();
        values.put(GEN_FIELD_CURRENTCONNECTIONID,Long.toString(this.gen_currentConnectionId));
        values.put(GEN_FIELD_CONNECTIONVALID,(this.gen_connectionValid ? "1" : "0"));
        return values;
    }

    /**
     * Return an array that gives the column index in the cursor for each field defined
     * @param cursor Database cursor over some columns, possibly including this table
     * @return array of column indices; -1 if the column with that id is not in cursor
     */
    public int[] Gen_columnIndices(android.database.Cursor cursor) {
        int[] result=new int[GEN_COUNT];
        result[0] = cursor.getColumnIndex(GEN_FIELD_CURRENTCONNECTIONID);
        result[1] = cursor.getColumnIndex(GEN_FIELD_CONNECTIONVALID);
        return result;
    }

    /**
     * Populate one instance from a cursor 
     */
    public void Gen_populate(android.database.Cursor cursor,int[] columnIndices) {
        if ( columnIndices[GEN_ID_CURRENTCONNECTIONID] >= 0 && ! cursor.isNull(columnIndices[GEN_ID_CURRENTCONNECTIONID])) {
            gen_currentConnectionId = cursor.getLong(columnIndices[GEN_ID_CURRENTCONNECTIONID]);
        }
        if ( columnIndices[GEN_ID_CONNECTIONVALID] >= 0 && ! cursor.isNull(columnIndices[GEN_ID_CONNECTIONVALID])) {
            gen_connectionValid = (cursor.getInt(columnIndices[GEN_ID_CONNECTIONVALID]) != 0);
        }
    }

    /**
     * Populate one instance from a ContentValues 
     */
    public void Gen_populate(android.content.ContentValues values) {
        gen_currentConnectionId = values.getAsLong(GEN_FIELD_CURRENTCONNECTIONID);
        gen_connectionValid = (values.getAsInteger(GEN_FIELD_CONNECTIONVALID) != 0);
    }
}
