// This class was generated from com.antlersoft.patchyamp.db.IPlayingList by a tool
// Do not edit this file directly! PLX THX
package com.antlersoft.patchyamp.db;

public class PlayingList extends com.antlersoft.android.dbimpl.IdImplementationBase implements IPlayingList {

    public static final String GEN_TABLE_NAME = "PLAYING_LIST";
    public static final int GEN_COUNT = 4;

    // Field constants
    public static final String GEN_FIELD__ID = "_id";
    public static final int GEN_ID__ID = 0;
    public static final String GEN_FIELD_MEDIAID = "MEDIAID";
    public static final int GEN_ID_MEDIAID = 1;
    public static final String GEN_FIELD_NOWPLAYINGINDEX = "NOWPLAYINGINDEX";
    public static final int GEN_ID_NOWPLAYINGINDEX = 2;
    public static final String GEN_FIELD_LISTCONTENTID = "LISTCONTENTID";
    public static final int GEN_ID_LISTCONTENTID = 3;

    // SQL Command for creating the table
    public static String GEN_CREATE = "CREATE TABLE PLAYING_LIST (" +
            "_id INTEGER PRIMARY KEY AUTOINCREMENT," +
            "MEDIAID TEXT," +
            "NOWPLAYINGINDEX INTEGER," +
            "LISTCONTENTID INTEGER" +
            ")";

    // Members corresponding to defined fields
    private long gen__Id;
    private String gen_mediaId;
    private long gen_nowPlayingIndex;
    private long gen_listContentId;

    public PlayingList()
    {
        gen_nowPlayingIndex = -1;
        gen_listContentId = -1;
    }

    public static final com.antlersoft.android.dbimpl.NewInstance<PlayingList> GEN_NEW = new com.antlersoft.android.dbimpl.NewInstance<PlayingList>() {
        public PlayingList get() {
            return new PlayingList();
        }
    }
            ;
    @Override
    public String Gen_tableName() { return GEN_TABLE_NAME; }

    // Field accessors
    public long get_Id() { return gen__Id; }
    public void set_Id(long arg__Id) { gen__Id = arg__Id; }
    public String getMediaId() { return gen_mediaId; }
    public void setMediaId(String arg_mediaId) { gen_mediaId = arg_mediaId; }
    public long getNowPlayingIndex() { return gen_nowPlayingIndex; }
    public void setNowPlayingIndex(long arg_nowPlayingIndex) { gen_nowPlayingIndex = arg_nowPlayingIndex; }
    public long getListContentId() { return gen_listContentId; }
    public void setListContentId(long arg_listContentId) { gen_listContentId = arg_listContentId; }

    public android.content.ContentValues Gen_getValues() {
        android.content.ContentValues values=new android.content.ContentValues();
        values.put(GEN_FIELD__ID,Long.toString(this.gen__Id));
        values.put(GEN_FIELD_MEDIAID,this.gen_mediaId);
        values.put(GEN_FIELD_NOWPLAYINGINDEX,Long.toString(this.gen_nowPlayingIndex));
        values.put(GEN_FIELD_LISTCONTENTID,Long.toString(this.gen_listContentId));
        return values;
    }

    /**
     * Return an array that gives the column index in the cursor for each field defined
     * @param cursor Database cursor over some columns, possibly including this table
     * @return array of column indices; -1 if the column with that id is not in cursor
     */
    public int[] Gen_columnIndices(android.database.Cursor cursor) {
        int[] result=new int[GEN_COUNT];
        result[0] = cursor.getColumnIndex(GEN_FIELD__ID);
        // Make compatible with database generated by older version of plugin with uppercase column name
        if (result[0] == -1) {
            result[0] = cursor.getColumnIndex("_ID");
        }
        result[1] = cursor.getColumnIndex(GEN_FIELD_MEDIAID);
        result[2] = cursor.getColumnIndex(GEN_FIELD_NOWPLAYINGINDEX);
        result[3] = cursor.getColumnIndex(GEN_FIELD_LISTCONTENTID);
        return result;
    }

    /**
     * Populate one instance from a cursor
     */
    public void Gen_populate(android.database.Cursor cursor,int[] columnIndices) {
        if ( columnIndices[GEN_ID__ID] >= 0 && ! cursor.isNull(columnIndices[GEN_ID__ID])) {
            gen__Id = cursor.getLong(columnIndices[GEN_ID__ID]);
        }
        if ( columnIndices[GEN_ID_MEDIAID] >= 0 && ! cursor.isNull(columnIndices[GEN_ID_MEDIAID])) {
            gen_mediaId = cursor.getString(columnIndices[GEN_ID_MEDIAID]);
        }
        if ( columnIndices[GEN_ID_NOWPLAYINGINDEX] >= 0 && ! cursor.isNull(columnIndices[GEN_ID_NOWPLAYINGINDEX])) {
            gen_nowPlayingIndex = cursor.getLong(columnIndices[GEN_ID_NOWPLAYINGINDEX]);
        }
        if ( columnIndices[GEN_ID_LISTCONTENTID] >= 0 && ! cursor.isNull(columnIndices[GEN_ID_LISTCONTENTID])) {
            gen_listContentId = cursor.getLong(columnIndices[GEN_ID_LISTCONTENTID]);
        }
    }

    /**
     * Populate one instance from a ContentValues
     */
    public void Gen_populate(android.content.ContentValues values) {
        gen__Id = values.getAsLong(GEN_FIELD__ID);
        gen_mediaId = values.getAsString(GEN_FIELD_MEDIAID);
        gen_nowPlayingIndex = values.getAsLong(GEN_FIELD_NOWPLAYINGINDEX);
        gen_listContentId = values.getAsLong(GEN_FIELD_LISTCONTENTID);
    }
}

